### ISSUE TITLE
Can’t find variable: s error on iOS 

### ISSUE THREAD

**Issue by That1Gamer64** [0x000011b/characterai-dumper#5]
Hi, I’ve been trying to back up my chat data via mobile (iPad specifically), I’ve installed a bunch of plugins that I needed but now I keep getting a “can’t find variable: s” error every time I try. other times it just freezes at “got chat history” and won’t proceed from there, or at “configuring intercepts” it gives multiple script errors and eventually “null”
![381C8BA1-99F4-4E53-AF30-A58112D61639](https://user-images.githubusercontent.com/123976269/215541912-8690ae39-ebf6-4cb9-ba67-26868ed533f9.jpeg)
. I’m not exactly sure what I could be doing wrong or how to fix this, and I can’t figure out a way to change my password to access it on a PC so I’m kinda stuck at the moment 

![3A3B2E37-789C-44A5-91B0-F16B4670C6E6](https://user-images.githubusercontent.com/123976269/215536126-7181e691-efb0-4055-888a-a88c9bf9cb23.jpeg)

**Comment by 0x000011b** [comment]
Unfortunately I'm not really sure what's going on there. From the stack trace, it looks like the error might be related to some library called [eruda](https://www.npmjs.com/package/eruda)? I don't use it in the userscript at all though, so I'm assuming it might be some bad interaction between the plugins you said you've installed?

**Comment by That1Gamer64** [comment]
Oh shoot, really? When I first started trying it said I needed the Eruda plug-in or else it wouldn’t even let me do anything. I actually just figured out I just made the account with a dud google account so I might be able to try use this through a different device and see if I have an easier time.

**Comment by 0x000011b** [comment]
Yep. If something said that it needed eruda to run, it's most certainly not my userscript. I'm not really sure how userscripts work on iOS, but I assume it might be related to whatever you needed to install to get userscript support on Safari?

Although yeah, if you can just use a desktop it'd probably be a lot easier. I don't have any iOS devices to test on so there's zero guarantees that it'd work there even if you fixed the eruda stuff.

**Comment by That1Gamer64** [comment]
Alright so I’ve been trying to do it through android now (kiwi browser with grease monkey as others have recommended) but I still can’t seem to get the download button to appear, and this time I can’t even figure out why it’s not working, even though I installed it properly.

**Comment by That1Gamer64** [comment]
Another update, I’ve been trying to do it on my PC (Firefox with Violentmonkey) only for the same result, and when bringing up inspect element’s console commands all it says is caching for the character info and chat histories for my profile and won’t progress from there, which is really confusing me. I’m not sure if there’s something I’m doing wrong or not but I can’t seem to get it.

**Comment by 0x000011b** [comment]
From the screenshot you've sent earlier, it says that it's caching character info for one character, but caching chat histories for some other unrelated character. Is that also what's happening on your PC? If so, that's why the link isn't showing up. It needs both the character info + chat histories for the _same_ character so it can create the file. Although this confused me a bit:

> [...] all it says is caching for the character info and chat histories for my profile

It should be caching things for the character you want to export, not your profile. Unless they've changed their API around. Can you show a screenshot of the DevTools console?

**Comment by That1Gamer64** [comment]
apologies for the picture off a screen, my screen cap button on my laptop isn’t working. This is what I’m getting in particular from the devtools console, I’m not sure what could be causing it but it doesn’t do anything beyond this nor shows the download button. Thing is, I only have a chat history with this one character (two different sets of messages in particular) so I’m not sure what else it could be trying to get.

![4970AC60-3DD7-4771-B90B-DAAE432A8817](https://user-images.githubusercontent.com/123976269/215827563-a23929c3-c596-418b-94b0-8fa3de6f4885.jpeg)

**Comment by 0x000011b** [comment]
Yeah, for some reason it's as if it was two different characters so the userscript thinks it doesn't have all the data, and the link doesn't get created. Was this character renamed after being created, or something of the sorts?

**Comment by That1Gamer64** [comment]
No, the character wasn’t. My friend created this one specifically for me, and after she made it she only shared the link with me, with the last thing she did with it being her backing the bot up with the dumper herself (alongside her other bots) though she hasn’t taken them down yet (as she isn’t sure about what to do with them yet)

**Comment by That1Gamer64** [comment]
Hi again;

been trying again all week on the dumper and still having the same issue on my pc (gets stuck caching character and chat histories) and I’m still not certain what exactly could be wrong. I’m not exactly very good at coding, so I’m not sure if there’s a specific line I should change to make it work. My friend was able to successfully give me the .json for the character dump of the character so I’m not sure if there’s something in there that could give any hints as to what could be wrong or not, but otherwise I’m stuck on what could be going wrong (which sucks bc I’d love to import/back up the chats I have with this character)

**Comment by 0x000011b** [comment]
Hey! Apologies for the delayed response - been dealing with the other fronts of the project for a bit. Since I can't reproduce this locally to figure out why the same bot seems to have two different names behind the scenes, I think your best bet here is to just use your browser's DevTools to download the raw responses from the API.

Basically, open up DevTools (usually F12), head over to the Network tab, then visit the page where you'd expect the download links to show up. You should be seeing some requests going out, and should specifically look for "histories" (for the messages themselves) and "info" (for the bot's basic information):

<img src="https://user-images.githubusercontent.com/121980126/213590585-45102e24-81d4-416c-83cb-18ebd4bd4bcb.png" />

 You can save the raw responses for those two requests, their contents will be very similar to what the userscript would generate.

**Comment by That1Gamer64** [comment]
Hi again;

trying to go through dev tools like you suggested and… I’m not seeing either of the two requests you mentioned. Here’s a picture of what I’m getting; I’m not exactly sure why the two requests you said to look for aren’t appearing but I’m frankly stumped as to why they aren’t coming up for me or what I should do from here.
![D4657401-BA6D-46E1-943F-A87E128B888A](https://user-images.githubusercontent.com/123976269/219968527-edf7c68d-0cf0-4eb7-a1cb-0f9e117e1c50.jpeg)

**Comment by RapsosK** [comment]
![Screenshot (1483)](https://user-images.githubusercontent.com/129937981/230016344-e75ebe4f-479b-4959-a7d8-8a823a7bd15a.png)
![Screenshot (1484)](https://user-images.githubusercontent.com/129937981/230016356-6e31e215-e6e7-4ed2-863a-5edae41f1772.png)


its been a year please help.
